### PR TITLE
Files

### PR DESCRIPTION
**Pull request by gedyzed**

### CODE REVIEW

**Review by DawitSishu — CHANGES_REQUESTED** [review]
### Changes Requested: 
Screenshot_2024-01-08_15-09-11
## As you can see in the work you did above the images are missing please include them.

**Comment by gedyzed** [comment]
I have fixed the issue that you've told me to fix.

**Comment by gedyzed** [comment]
I think now it is ready to be merged

**Review by DawitSishu — APPROVED** [review]
## Pull Request Ready for Merge! 🚀
7E2d

Your hard work and dedication have paid off! 🎉 The pull request you've been working on is now ready and approved for merging. Fantastic job! 🙌

Take a moment to savor this accomplishment, and when you're ready, feel free to merge the pull request. If you have any questions or if there's anything else you'd like to discuss, I'm here!

Cheers to your success! 🥳

**Pull request merged**
